SET SESSION FOREIGN_KEY_CHECKS=0;

/* DROP TABLES */

DROP TABLE IF EXISTS DS_MEDIA_TX;
DROP TABLE IF EXISTS DS_COMMENT_TX;
DROP TABLE IF EXISTS DS_EMOTION_TX;
DROP TABLE IF EXISTS DS_BOARD_TX;
DROP TABLE IF EXISTS DS_STUDENT_SUB1_TX;
DROP TABLE IF EXISTS DS_EVENT_TX;
DROP TABLE IF EXISTS DS_EVNT_REG_TX;
DROP TABLE IF EXISTS DS_FAVORITE_TX;
DROP TABLE IF EXISTS DS_MYGROUP_TX;
DROP TABLE IF EXISTS DS_GROUP_TX;
DROP TABLE IF EXISTS DS_NEWS_TX;
DROP TABLE IF EXISTS DS_RCMMD_TX;
DROP TABLE IF EXISTS DS_SNS_CONSULT_TX;
DROP TABLE IF EXISTS DS_SCHOOL_COURSES_TX;
DROP TABLE IF EXISTS DS_VIWECNT_TX;
DROP TABLE IF EXISTS DS_SCHOOL_REF_TX;
DROP TABLE IF EXISTS DS_SCHOOL_BRANCH_TX;
DROP TABLE IF EXISTS DS_SCHOOL_SUB2_TX;
DROP TABLE IF EXISTS DS_SCHOOL_SUB1_TX;
DROP TABLE IF EXISTS DS_SCHOOL_IMG_TX;
DROP TABLE IF EXISTS DS_SCHOOL_KEY_TX;
DROP TABLE IF EXISTS DS_SCHOOL_TX;
DROP TABLE IF EXISTS DS_STUDENT_SUB2_TX;
DROP TABLE IF EXISTS DS_STUDENT_SUB1_TX;
DROP TABLE IF EXISTS DS_STUDENT_TX;
DROP TABLE IF EXISTS DS_SEARCH_UNIV_SUB_TX;
DROP TABLE IF EXISTS DS_SEARCH_UNIV_TX;
DROP TABLE IF EXISTS DS_USER_SPEC_MST;
DROP TABLE IF EXISTS DS_USER_TX;
DROP TABLE IF EXISTS DS_CODE_MST;
DROP TABLE IF EXISTS DS_VIEWCNT_TX;
DROP TABLE IF EXISTS DS_SEARCH_VOCA_TX;
DROP TABLE IF EXISTS DS_HIGHSCHOOL_TX;
DROP TABLE IF EXISTS DS_ACCESS_TX;
DROP TABLE IF EXISTS DS_SCHMID_BASE;
DROP TABLE IF EXISTS DS_SCHMID_BASEINFO;
DROP TABLE IF EXISTS DS_SEARCH_HIGH_TX;
DROP TABLE IF EXISTS DS_BLOG_TX;
DROP VIEW IF EXISTS DS_SCHOOL_LIST_VIEW;



/* CREATE TABLES */

CREATE TABLE DS_BOARD_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	BOARD_ID VARCHAR(10) NOT NULL,
	STUDENT_ID VARCHAR(15) NOT NULL,
	GROUP_ID VARCHAR(10) NOT NULL,
	BOARD_TYPE TINYINT,
	CONTENTS VARCHAR(2000),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (BOARD_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_COMMENT_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	STUDENT_ID VARCHAR(15) NOT NULL,
	BOARD_ID VARCHAR(10) NOT NULL,
	COMMENTS VARCHAR(2000),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_STUDENT_SUB1_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	STUDENT_ID VARCHAR(15) NOT NULL,
	CUR_SCHOOL_TYPE1 TINYINT COMMENT '초등/중/고등/대학교 등',
	CUR_SCHOOL_TYPE2 TINYINT COMMENT '사립/국립/특수 등',
	CUR_SCHOOL_CODE VARCHAR(20),
	CUR_SCHOOL_NAME VARCHAR(200),
	CUR_SCHOOL_GRADE TINYINT,
	LANG_SCORE DECIMAL(3,1),
	ENG_SCORE DECIMAL(3,1),
	HIST_SCORE DECIMAL(3,1),
	CIVIL_SCORE DECIMAL(3,1),
	MAT_SCORE DECIMAL(3,1),
	SCI_SCORE DECIMAL(3,1),
	RANK VARCHAR(50),
	REMARKS VARCHAR(2048),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(15),
	PRIMARY KEY (STUDENT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_EMOTION_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	BOARD_ID VARCHAR(10) NOT NULL,
	EMOTION_H INT,
	EMOTION_F INT,
	EMOTION_K INT,
	EMOTION_N INT,
	EMOTION_S INT,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_EVENT_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	EVT_ID VARCHAR(10) NOT NULL,
	STUDENT_ID VARCHAR(15) NOT NULL,
	GROUP_ID VARCHAR(10) NOT NULL,
	EVT_TITLE VARCHAR(1024),
	EVT_TYPE TINYINT,
	EVT_REG TINYINT DEFAULT 0,
	EVT_CATEGORY TINYINT,
	EVT_DATE_S VARCHAR(10),
	EVT_DATE_E VARCHAR(10),
	EVT_TIME_S VARCHAR(5),
	EVT_TIME_E VARCHAR(5),
	EVT_LOCATION VARCHAR(1000),
	EVT_CONTENTS VARCHAR(4096),
	REMARKS VARCHAR(2048),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (EVT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE DS_EVNT_REG_TX (
	IDX 		INT AUTO_INCREMENT PRIMARY KEY,
	EVT_ID		VARCHAR(15) NOT NULL,
	STUDENT_ID	VARCHAR(15) NOT NULL,
	REG_DATE	DATETIME
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE DS_FAVORITE_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	FAVORITE_ID VARCHAR(10) NOT NULL,
	STUDENT_ID VARCHAR(15) NOT NULL,
	SB_ID VARCHAR(15) NOT NULL,
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (FAVORITE_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_GROUP_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	GROUP_ID VARCHAR(10) NOT NULL,
	STUDENT_ID VARCHAR(15) NOT NULL,
	GROUP_NAME VARCHAR(50),
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (GROUP_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_MEDIA_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	BOARD_ID VARCHAR(10) NOT NULL,
	MEDIA_TYPE TINYINT,
	URL VARCHAR(1000),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_MYGROUP_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	GROUP_ID VARCHAR(10) NOT NULL,
	STUDENT_ID VARCHAR(10),
	MYSTUDENT_ID VARCHAR(10),
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_NEWS_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	SCHOOL_ID VARCHAR(15),
	-- 1: NEWS
	-- 2: EVENTS
	-- 8: NEWS BY ADMIN
	-- 9: EVENTS BY ADMIN
	NEWS_TYPE TINYINT COMMENT '1: NEWS 2: EVENTS',
	EVENT_REG VARCHAR(50),
	NEWS_TITLE VARCHAR(1024),
	NEWS_CONTENTS VARCHAR(4096),
	NEWS_HIT INT DEFAULT 0,
	IS_HTML CHAR(1) DEFAULT 'N',
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(15),
	DEL_DATE TIMESTAMP,
	DEL_ID VARCHAR(15),
	DEL_FLG TINYINT,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_RCMMD_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	RCMMD_ID VARCHAR(10) NOT NULL,
	STUDENT_ID VARCHAR(15) NOT NULL,
	SB_ID VARCHAR(15) NOT NULL,
	RCMMD_TYPE VARCHAR(20),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	LAST_R_DATE TIMESTAMP,
	PRIMARY KEY (RCMMD_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_BRANCH_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	SB_ID VARCHAR(10) NOT NULL,
	SCHOOL_ID VARCHAR(15) NOT NULL,
	SB_TYPE TINYINT,
	SB_CATEGORY TINYINT COMMENT '1-ELEMENTARY
2-MIDDLE
3-HIGH
4-COLLEGE
5-UNIVERSITY
6-GRADUATE
7-ABROAD
',
	SB_ORD TINYINT,
	SB_NAME VARCHAR(200),
	SB_TITLE1 VARCHAR(200),
	SB_TITLE2 VARCHAR(200),
	SB_CONTENTS VARCHAR(2048),
	SB_FEATURES VARCHAR(2048),
	SB_POLICY VARCHAR(2048),
	SB_TEL VARCHAR(50),
	SB_FAX VARCHAR(50),
	SB_DEPT VARCHAR(100),
	SB_ZIPCODE VARCHAR(20),
	SB_PREFECTURE_ID VARCHAR(2),
	SB_ADDRESS1 VARCHAR(200),
	SB_ADDRESS2 VARCHAR(200),
	SB_ADDRESS3 VARCHAR(200),
	SB_ADDRESS4 VARCHAR(200),
	SB_ACCESS VARCHAR(1024),
	PHOTO1_NAME VARCHAR(200),
	PHOTO1_SIZE BIGINT,
	ORG1_NAME VARCHAR(200),
	PHOTO2_NAME VARCHAR(200),
	PHOTO2_SIZE BIGINT,
	ORG2_NAME VARCHAR(200),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(10),
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (SB_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_SUB2_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	SCHOOL_ID VARCHAR(15) NOT NULL,
	CHR_FNAME VARCHAR(50),
	CHR_LNAME VARCHAR(50),
	CHR_DEPT VARCHAR(200),
	CHR_TEL VARCHAR(50),
	CHR_FAX VARCHAR(30),
	CHR_FB VARCHAR(100),
	CHR_TW VARCHAR(100),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(15),
	PRIMARY KEY (SCHOOL_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_COURSES_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	SB_ID VARCHAR(10) NOT NULL,
	CURS_ORD TINYINT,
	CURS_TITLE VARCHAR(200),
	CURS_CONTENTS1 VARCHAR(1024),
	CURS_CONTENTS2 VARCHAR(2048),
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_SUB1_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	SCHOOL_ID VARCHAR(15) NOT NULL,
	FEATURES VARCHAR(2048),
	COURSES VARCHAR(2048),
	FEE VARCHAR(2048),
	FINANCIAL VARCHAR(2048),
	SELECTION VARCHAR(2048),
	ACCESS VARCHAR(2048),
	MAP VARCHAR(2048),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(10),
	PRIMARY KEY (SCHOOL_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_IMG_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	SCHOOL_ID VARCHAR(15) NOT NULL,
	IMG_ORD INT,
	FILENAME VARCHAR(100),
	FILESIZE BIGINT,
	ORIGIN_NAME VARCHAR(200),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_KEY_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	SB_ID VARCHAR(15) NOT NULL,
	KEYCODE VARCHAR(10) NOT NULL,
	KEYWORD VARCHAR(50),
	DATA_TYPE TINYINT,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_REF_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	SB_ID VARCHAR(10) NOT NULL,
	FILENAME1 VARCHAR(200),
	FILESIZE1 BIGINT,
	FILETYPE1 TINYINT,
	DOWNCNT1 INT,
	FILENAME2 VARCHAR(200),
	FILESIZE2 BIGINT,
	FILETYPE2 TINYINT,
	DOWNCNT2 INT,
	FILENAME3 VARCHAR(200),
	FILESIZE3 BIGINT,
	FILETYPE3 TINYINT,
	DOWNCNT3 INT,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (SB_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SCHOOL_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	SCHOOL_ID VARCHAR(15) NOT NULL,
	SCHOOL_NAME VARCHAR(200),
	SCHOOL_SHORT_NAME VARCHAR(200),
	HIRAGANA VARCHAR(200),
	SCHOOL_TYPE VARCHAR(10),
	SCHOOL_CATEGORY VARCHAR(15),
	TITLE1 VARCHAR(200),
	TITLE2 VARCHAR(500),
	CONTENTS VARCHAR(2048),
	BUILT_YEAR VARCHAR(10),
	HOMEPAGE VARCHAR(100),
	LOC_CODE VARCHAR(15),
	ZIPCODE VARCHAR(10),
	ADDRESS1 VARCHAR(200),
	ADDRESS2 VARCHAR(200),
	ADDRESS3 VARCHAR(200),
	ADDRESS4 VARCHAR(200),
	STD_INFO VARCHAR(2048),
	LOGONAME VARCHAR(100),
	LOGOSIZE BIGINT,
	ORIGIN_NAME VARCHAR(200),
	PAID_TYPE TINYINT,
	REMARKS VARCHAR(2048),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(10),
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (SCHOOL_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SNS_CONSULT_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	STUDENT_ID VARCHAR(15) NOT NULL,
	SB_ID VARCHAR(15) NOT NULL,
	CONST_STATUS TINYINT DEFAULT 1,
	CONTENTS VARCHAR(2048),
	INS_DATE TIMESTAMP,
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_STUDENT_SUB2_TX 
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	STUDENT_ID VARCHAR(15) NOT NULL,
	SCHOOL1 VARCHAR(100),
	SCHOOL2 VARCHAR(100),
	SCHOOL3 VARCHAR(100),
	LOCATION1 VARCHAR(100),
	LOCATION2 VARCHAR(100),
	LOCATION3 VARCHAR(100),
	SUBJECT1 VARCHAR(100),
	SUBJECT2 VARCHAR(100),
	SUBJECT3 VARCHAR(100),
	JOB1 VARCHAR(100),
	JOB2 VARCHAR(100),
	JOB3 VARCHAR(100),
	FIELD1 VARCHAR(100),
	FIELD2 VARCHAR(100),
	FIELD3 VARCHAR(100),
	REMARKS VARCHAR(2048),
	SCHOOL_ORD TINYINT,
	SUBJECT_ORD TINYINT,
	LOCATION_ORD TINYINT,
	JOB_ORD TINYINT,
	FIELD_ORD TINYINT,
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (STUDENT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_STUDENT_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	STUDENT_ID VARCHAR(15) NOT NULL,
	FNAME VARCHAR(50),
	LNAME VARCHAR(50),
	LOCATION VARCHAR(10),
	GENDER VARCHAR(1),
	FILENAME VARCHAR(200),
	FILESIZE BIGINT,
	CURRENT_TYPE TINYINT,
	RCMMD_TYPE TINYINT,
	ZIPCODE VARCHAR(10),
	ADDRESS1 VARCHAR(200),
	ADDRESS2 VARCHAR(200),
	ADDRESS3 VARCHAR(200),
	ADDRESS4 VARCHAR(200),
	BIRTH_Y VARCHAR(4),
	BIRTH_M VARCHAR(2),
	BIRTH_D VARCHAR(2),
	REMARKS VARCHAR(2048),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(15),
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (STUDENT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SEARCH_UNIV_SUB_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	AGRICULTURAL VARCHAR(300),
	MEDICALWELFARE VARCHAR(300),
	CULINARY VARCHAR(300),
	BARBERA VARCHAR(300),
	JAPANESELANGUAGE VARCHAR(300),
	ANIMAL VARCHAR(300),
	NOSHOW VARCHAR(300),
	NOADMIT VARCHAR(300),
	CLOSE VARCHAR(300),
	SHUT VARCHAR(300),
	ADMITCOURSE VARCHAR(300),
	BUSINESSSUBJECT VARCHAR(300),
	INTEGRATION VARCHAR(300),
	REDUNDANCY VARCHAR(300),
	NOOPEN VARCHAR(300),
	ID_NOREDUNDANCY INT,
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_SEARCH_UNIV_TX
(
	SCH_ID VARCHAR(15) NOT NULL PRIMARY KEY,
	ID INT NOT NULL UNIQUE,
	SCHOOL_ID VARCHAR(15),
	NAME VARCHAR(200),
	MEMO VARCHAR(200),
	YOMIGANA VARCHAR(200),
	SHT_NAME VARCHAR(200),
	SHT_NAME_YG VARCHAR(200),
	SCH_CATE_ID VARCHAR(200),
	SCH_FOUNDER_ID VARCHAR(200),
	URL_PC VARCHAR(200),
	URL_MOBILE VARCHAR(200),
	URL_CAREER_PC VARCHAR(200),
	EMAIL VARCHAR(200),
	ZIPCODE VARCHAR(50),
	PREFECTURE_ID VARCHAR(200),
	ADDRESS VARCHAR(200),
	ADDRESS1 VARCHAR(200),
	ADDRESS2 VARCHAR(200),
	ADDRESS3 VARCHAR(200),
	ADDRESS4 VARCHAR(200),
	TEL VARCHAR(50),
	TEL_MEMO VARCHAR(300),
	FREEDIAL VARCHAR(100),
	FREEDIAL_MEMO VARCHAR(300),
	FAX VARCHAR(50),
	FOUNDYEAR VARCHAR(20),
	MEMO_PAST VARCHAR(500),
	PAMPHLET VARCHAR(200),
	PAMPHLETSTART VARCHAR(100),
	SCH_STATUS_CONTRACT INT,
	SCH_STATUS INT,
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_USER_SPEC_MST
(
	IDX INT NOT NULL AUTO_INCREMENT,
	COUNTY VARCHAR(5),
	CATEGORY VARCHAR(10),
	CODE VARCHAR(15),
	TYPE1 VARCHAR(100),
	TYPE2 VARCHAR(100),
	TYPE3 VARCHAR(100),
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_USER_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	USER_ID VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100),
	PWD VARCHAR(50),
	JOIN_TYPE TINYINT,
	MEM_TYPE TINYINT,
	REG_STATUS VARCHAR(10),
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(15),
	DEL_FLG TINYINT DEFAULT 0,
	LAST_LOGIN_DATE TIMESTAMP,
	PRIMARY KEY (USER_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE DS_VIEWCNT_TX
(
	IDX INT NOT NULL AUTO_INCREMENT UNIQUE,
	SB_ID VARCHAR(15) NOT NULL,
	VIEWCNT INT,
	REALCNT INT,
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	PRIMARY KEY (SB_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE DS_ACCESS_TX (
	IDX INT AUTO_INCREMENT PRIMARY KEY,
	SCH_CNT	BIGINT,
	STD_CNT	BIGINT,
	ACCESS_DATE VARCHAR(8)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*
 * LOAD DATA LOCAL INFILE 'C:/USERS/KENNETH/DOWNLOADS/KEN_ALL/KEN_ALL_2.TXT'
INTO TABLE ZIPMASTER
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
DROP TABLE IF EXISTS ZIPMASTER;
CREATE TABLE ZIPMASTER (
	PUBLICCODE CHAR(5) NOT NULL,
	OLDZIPCODE CHAR(5) NOT NULL,
	ZIPCODE CHAR(7) NOT NULL,
	PREFECTUREKANA VARCHAR(10),
	CITYKANA VARCHAR(100),
	TOWNKANA VARCHAR(100),
	PREFECTURE VARCHAR(10),
	CITY VARCHAR(200),
	TOWN VARCHAR(200),
	TOWNDIVIDEFLG TINYINT(1),
	KOAZABANCHIFLG TINYINT(1),
	TYOUMEFLG TINYINT(1),
	HASSOMETOWNFLG TINYINT(1),
	UPDATESTATE TINYINT(1),
	UPDATERESON TINYINT(1),
	PRIMARY KEY (ZIPCODE)
);
*/

	
CREATE TABLE DS_CODE_MST
(
	IDX INT NOT NULL UNIQUE AUTO_INCREMENT,
	CODE VARCHAR(10) NOT NULL,
	TYPE VARCHAR(15),
	CODE_STR VARCHAR(50),
	PRIMARY KEY (CODE)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
	
CREATE TABLE DS_SEARCH_VOCA_TX
(
	SCH_ID VARCHAR(15) NOT NULL,
	SCHOOL_ID VARCHAR(15),
	CHARGER_BRN VARCHAR(15),
	CUST_ID VARCHAR(15),
	CUST_NAME VARCHAR(200),
	HURIGANA VARCHAR(400),
	SCH_FOUNDER_ID VARCHAR(200),
	ZIPCODE VARCHAR(10),
	ADDRESS1 VARCHAR(50),
	PREFECTURE_ID VARCHAR(2),
	ADDRESS2 VARCHAR(200),
	TEL VARCHAR(100),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (SCH_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE DS_SEARCH_HIGH_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	SCH_ID VARCHAR(15),
	NAME VARCHAR(200),
	SB_TYPE VARCHAR(2),
	OP_TIME VARCHAR(20),
	HIRAGANA VARCHAR(200),
	SCH_FOUNDER_ID VARCHAR(2),
	ZIPCODE VARCHAR(10),
	PREFECTURE_ID VARCHAR(2),
	ADDRESS1 VARCHAR(200),
	ADDRESS2 VARCHAR(200),
	ADDRESS3 VARCHAR(200),
	ADDRESS4 VARCHAR(200),
	CHR_DEPT VARCHAR(200),
	CHR_TEL VARCHAR(100),
	CHR_FAX VARCHAR(100),
	MEMO VARCHAR(2048),
	INS_DATE TIMESTAMP,
	UPD_DATE TIMESTAMP,
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE DS_BLOG_TX
(
	IDX INT NOT NULL AUTO_INCREMENT,
	STUDENT_ID VARCHAR(15) NOT NULL,
	BLOG_TYPE TINYINT NOT NULL,
	SHOW_FLG TINYINT NOT NULL DEFAULT 0,
	SCHOOL_ID VARCHAR(15),
	TITLE VARCHAR(1024) NOT NULL,
	CONTENTS TEXT NOT NULL,
	UPD_DATE TIMESTAMP,
	UPD_ID VARCHAR(15),
	DEL_DATE TIMESTAMP,
	DEL_FLG TINYINT DEFAULT 0,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE DS_SCHMID_BASE (
	IDX				INT PRIMARY KEY AUTO_INCREMENT,
	SCH_ID			VARCHAR(15),
	ID				INT,
	SCHOOL_NAME		VARCHAR(200),
	SCH_CATEGORY	VARCHAR(50),
	SCH_GUBUN		VARCHAR(10),
	HIRAGANA		VARCHAR(400),
	PREFECTURE_ID	INT(2),
	ZIPCODE			VARCHAR(10),
	ADDRESS			VARCHAR(500),
	GOOGLE			VARCHAR(500),
	TEL				VARCHAR(100),
	URL				VARCHAR(100),
	INS_DATE		TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
	
CREATE TABLE DS_SCHMID_BASEINFO (
	IDX				INT PRIMARY KEY AUTO_INCREMENT,
	SCH_ID			VARCHAR(15),
	ID				INT,
	SCHOOL_NAME		VARCHAR(200),
	SCHOOL_COPY		VARCHAR(400),
	PRINCIPAL		VARCHAR(100),
	HISTORY			TEXT,
	SCH_COUNT		TEXT,
	STATION			TEXT,
	CURRICULUM		TEXT,
	START_TIME		VARCHAR(50),
	END_TIME		VARCHAR(50),
	SCH_EXPLAIN1	TEXT,
	HENSACHI		TEXT,
	GAKUHI			TEXT,
	INS_DATE		TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE ZIPMASTER
(
	PUBLICCODE CHAR(5),
	OLDZIPCODE CHAR(5),
	ZIPCODE CHAR(7),
	PREFECTUREKANA VARCHAR(10),
	CITYKANA VARCHAR(100),
	TOWNKANA VARCHAR(100),
	PREFECTURE VARCHAR(10),
	CITY VARCHAR(200),
	TOWN VARCHAR(200),
	TOWNDIVIDERFLG TINYINT,
	KOAZABANCHIFLG TINYINT,
	TYOUMEFLG TINYINT,
	HASSOMETOWNFLG TINYINT,
	UPDATESTATE TINYINT,
	UPDATERESON TINYINT
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE VIEW DS_SCHOOL_LIST_VIEW AS 
SELECT 	SCH_ID, SCHOOL_NAME, 2 AS SCHOOL_TYPE, 3 AS SCH_FOUNDER_ID, ZIPCODE, PREFECTURE_ID, ADDRESS, INS_DATE
FROM	DS_SCHMID_BASE
UNION
SELECT 	SCH_ID, NAME AS SCHOOL_NAME, 3 AS SCHOOL_TYPE, SCH_FOUNDER_ID, ZIPCODE, PREFECTURE_ID, CONCAT(ADDRESS1, ADDRESS2, ADDRESS3) AS ADDRESS, INS_DATE
FROM	DS_SEARCH_HIGH_TX
UNION
SELECT	SCH_ID, NAME AS SCHOOL_NAME, 4 AS SCHOOL_TYPE, SCH_FOUNDER_ID, ZIPCODE, PREFECTURE_ID, CONCAT(ADDRESS1, ADDRESS2, ADDRESS3) AS ADDRESS, INS_DATE
FROM	DS_SEARCH_UNIV_TX
UNION
SELECT	SCH_ID, CUST_NAME AS SCHOOL_NAME, 5 AS SCHOOL_TYPE, SCH_FOUNDER_ID, ZIPCODE, PREFECTURE_ID, CONCAT(ADDRESS1, ADDRESS2) AS ADDRESS, INS_DATE
FROM	DS_SEARCH_VOCA_TX
UNION
SELECT	SCHOOL_ID AS SCH_ID, SB_NAME AS SCHOOL_NAME, SB_TYPE AS SCHOOL_TYPE, SB_ID, SB_ZIPCODE, SB_PREFECTURE_ID, CONCAT(SB_ADDRESS1, SB_ADDRESS2) AS ADDRESS, INS_DATE
FROM	DS_SCHOOL_BRANCH_TX;

/*
RENAME TABLE DS_SCHOOL_DETAIL_TX TO DS_SCHOOL_SUB1_TX;
RENAME TABLE DS_SCHOOL_CHARGER_TX TO DS_SCHOOL_SUB2_TX;
RENAME TABLE DS_HIGHSCHOOL_TX TO DS_SEARCH_HIGH_TX;
RENAME TABLE DS_UNIVERSITY_TX TO DS_SEARCH_UNIV_TX;
RENAME TABLE DS_UNIVERSITY_ETC_TX TO DS_SEARCH_UNIV_SUB_TX;
RENAME TABLE DS_COLLEGE_BSC_TX TO DS_SEARCH_COLE_TX;
RENAME TABLE DS_VOCATIONAL_TX TO DS_SEARCH_VOCA_TX;
RENAME TABLE DS_CUR_SCHOOL_TX TO DS_STUDENT_SUB1_TX;
RENAME TABLE DS_SPECIFIC_TX TO DS_STUDENT_SUB2_TX;
*/

/* CREATE FOREIGN KEYS */

ALTER TABLE DS_MEDIA_TX
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES DS_BOARD_TX (BOARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_COMMENT_TX
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES DS_BOARD_TX (BOARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_EMOTION_TX
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES DS_BOARD_TX (BOARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_BOARD_TX
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES DS_GROUP_TX (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_EVENT_TX
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES DS_GROUP_TX (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_MYGROUP_TX
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES DS_GROUP_TX (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SNS_CONSULT_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_BRANCH_TX (SB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_COURSES_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_BRANCH_TX (SB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_VIEWCNT_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_BRANCH_TX (SB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_REF_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_BRANCH_TX (SB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_FAVORITE_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_BRANCH_TX (SB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_RCMMD_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_BRANCH_TX (SB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_BRANCH_TX
	ADD FOREIGN KEY (SCHOOL_ID)
	REFERENCES DS_SCHOOL_TX (SCHOOL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_SUB1_TX
	ADD FOREIGN KEY (SCHOOL_ID)
	REFERENCES DS_SCHOOL_TX (SCHOOL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_KEY_TX
	ADD FOREIGN KEY (SB_ID)
	REFERENCES DS_SCHOOL_TX (SCHOOL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_IMG_TX
	ADD FOREIGN KEY (SCHOOL_ID)
	REFERENCES DS_SCHOOL_TX (SCHOOL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_SUB2_TX
	ADD FOREIGN KEY (SCHOOL_ID)
	REFERENCES DS_SCHOOL_TX (SCHOOL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_COMMENT_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_FAVORITE_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_EVENT_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_GROUP_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_BOARD_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SNS_CONSULT_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_RCMMD_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE DS_STUDENT_SUB1_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_STUDENT_SUB2_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_STUDENT_TX (STUDENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SEARCH_UNIV_SUB_TX
	ADD FOREIGN KEY (IDX)
	REFERENCES DS_SEARCH_UNIV_TX (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_SCHOOL_TX
	ADD FOREIGN KEY (SCHOOL_ID)
	REFERENCES DS_USER_TX (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DS_STUDENT_TX
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES DS_USER_TX (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



